### PR TITLE
FLOE-240: Fixed sim

### PR DESCRIPTION
**Pull request by jhung**
Sim should now work in iBooks and Readium. But the sim is missing keyboard accessibility and includes all other Forces & Motion sims. This is a temporary solution until we can properly integrate a version of the sim that works with the keyboard.

### CODE REVIEW

**Comment by acheetham** [comment]
In your branch, all of the files in the html folder are now .xhtml; is this necessary?

**Comment by acheetham** [comment]
If the sim now includes all of the other sims, perhaps we should update the instructions to mention choosing the forces and motions one?

**Comment by acheetham** [comment]
The .smil file is still referring to .html files, so if we need to switch to .xhtml, that will have to be updated.

**Comment by jhung** [comment]
1. Only 03-forces-simulation-2.html file was renamed to .xhtml (FLOE-240-2 branch is being used, not FLOE-240 branch). Changing the extension to of 03- .html (and updating the TOC and package.opf files) causes the script to not appear in Readium but works fine in iBooks. Using .xhtml extension seems to matter for Readium.
2. Good point. I will update the text.
3. Got it, thanks.

**Pull request closed without merging**
